### ISSUE TITLE
Cannot parse some dnsstamps.

### ISSUE THREAD

**Issue by hongyi-zhao** [chrisss404/python-dnsstamps#1]
Hi,

Try this give me the following error:

$ dnsstamp.py parse sdns://AgUAAAAAAAAABzguOC44LjigHvYkz_9ea9O63fP92_3qVlRn43cpncfuZnUWbzAMwbkgdoAkR6AZkxo_AEMExT_cbBssN43Evo9zs5_ZyWnftEUKZG5zLmdvb2dsZQovZG5zLXF1ZXJ5
Unable to parse stamp <sdns://AgUAAAAAAAAABzguOC44LjigHvYkz_9ea9O63fP92_3qVlRn43cpncfuZnUWbzAMwbkgdoAkR6AZkxo_AEMExT_cbBssN43Evo9zs5_ZyWnftEUKZG5zLmdvb2dsZQovZG5zLXF1ZXJ5>

The above dns stamp is excerpted here:

https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v2/public-resolvers.md

google

Google DNS (anycast)

sdns://AgUAAAAAAAAABzguOC44LjigHvYkz_9ea9O63fP92_3qVlRn43cpncfuZnUWbzAMwbkgdoAkR6AZkxo_AEMExT_cbBssN43Evo9zs5_ZyWnftEUKZG5zLmdvb2dsZQovZG5zLXF1ZXJ5

Is this a bug of this tool?

Regards

**Comment by chrisss404** [comment]
Yes, you found a bug. Thanks for reporting.

Fixed with version 1.2.3.

```
dnsstamp.py parse sdns://AgUAAAAAAAAABzguOC44LjigHvYkz_9ea9O63fP92_3qVlRn43cpncfuZnUWbzAMwbkgdoAkR6AZkxo_AEMExT_cbBssN43Evo9zs5_ZyWnftEUKZG5zLmdvb2dsZQovZG5zLXF1ZXJ5
DoH DNS stamp
=============

DNSSEC: yes
No logs: no
No filter: yes
IP Address: 8.8.8.8
Hashes: [b'1ef624cfff5e6bd3baddf3fddbfdea565467e377299dc7ee6675166f300cc1b9', b'76802447a019931a3f004304c53fdc6c1b2c378dc4be8f73b39fd9c969dfb445']
Hostname: dns.google
Path: /dns-query
Bootstrap IPs: []

sdns://AgUAAAAAAAAABzguOC44LjigHvYkz_9ea9O63fP92_3qVlRn43cpncfuZnUWbzAMwbkgdoAkR6AZkxo_AEMExT_cbBssN43Evo9zs5_ZyWnftEUKZG5zLmdvb2dsZQovZG5zLXF1ZXJ5
```

BR
Christian
